name: base

run-name: ${{github.actor}} is running actions

on:
  push:
    branches: [ "main" ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
           mkdir ~/.npm-global
           npm config set prefix '~/.npm-global'
           export PATH=~/.npm-global/bin:$PATH
           npm install -g bats
           bats -v
